# Generated by Django 3.0.5 on 2020-05-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('origin_pdf', models.FileField(upload_to='formulario/upload')),
            ],
        ),
        migrations.CreateModel(
            name='PdfPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_text', models.CharField(max_length=100)),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=200)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=299)),
                ('pdf_page', models.IntegerField(default=1)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.GenPdf')),
            ],
        ),
    ]
